-- Demo seed data: suppliers, products, and 30 days of movement history

INSERT INTO "suppliers" ("id", "name", "contact_email", "lead_time_days", "delay_days", "delay_note") VALUES

(1, 'Acme Electronics', 'orders@acmeelectronics.example', 5, 3, 'Customs hold on latest container — shipment delayed 3 days'),
(2, 'NorthPoint Office Supply', 'sales@northpointoffice.example', 4, 0, NULL),
(3, 'Silverline Peripherals', 'wholesale@silverlineperipherals.example', 10, 0, NULL);

INSERT INTO "products" ("id", "sku", "name", "category", "supplier_id", "cost_cents", "price_cents", "quantity", "reorder_threshold", "target_coverage_days") VALUES

(1, 'SKU-0001-MECH', 'Mechanical Keyboard', 'Electronics', 1, 3200, 6900, 7, 10, 30),
(2, 'SKU-0002-27MO', '27" Monitor', 'Electronics', 1, 14000, 24900, 2, 8, 30),
(3, 'SKU-0003-USBC', 'USB-C Hub', 'Electronics', 3, 1800, 3900, 3, 12, 30),
(4, 'SKU-0004-WIRE', 'Wireless Mouse', 'Electronics', 3, 900, 2400, 9, 15, 30),
(5, 'SKU-0005-WEBC', 'Webcam 1080p', 'Electronics', 1, 2600, 5400, 6, 10, 30),
(6, 'SKU-0006-LAPT', 'Laptop Stand', 'Electronics', 3, 2100, 4500, 24, 8, 30),
(7, 'SKU-0007-WIRE', 'Wireless Charger', 'Electronics', 1, 1200, 2900, 31, 10, 30),
(8, 'SKU-0008-BLUE', 'Bluetooth Speaker', 'Electronics', 1, 3400, 6900, 18, 8, 30),
(9, 'SKU-0009-NOIS', 'Noise Cancelling Headphones', 'Electronics', 3, 6800, 12900, 11, 6, 30),
(10, 'SKU-0010-HDMI', 'HDMI Cable 2m', 'Electronics', 2, 400, 1200, 47, 15, 30),
(11, 'SKU-0011-USBC', 'USB-C Docking Station', 'Electronics', 3, 5200, 9900, 8, 6, 30),
(12, 'SKU-0012-PORT', 'Portable SSD 1TB', 'Electronics', 3, 6100, 11900, 14, 6, 30),
(13, 'SKU-0013-ERGO', 'Ergonomic Mouse Pad', 'Electronics', 2, 700, 1800, 29, 10, 30),
(14, 'SKU-0014-RING', 'Ring Light', 'Electronics', 1, 1900, 3900, 16, 6, 30),
(15, 'SKU-0015-USBM', 'USB Microphone', 'Electronics', 3, 4200, 7900, 10, 6, 30),
(16, 'SKU-0016-GRAP', 'Graphics Tablet', 'Electronics', 3, 7300, 13900, 7, 4, 30),
(17, 'SKU-0017-SMAR', 'Smart Plug', 'Electronics', 1, 1100, 2400, 38, 12, 30),
(18, 'SKU-0018-WIFI', 'WiFi 6 Router', 'Electronics', 1, 5900, 10900, 12, 6, 30),
(19, 'SKU-0019-POWE', 'Power Bank 20000mAh', 'Electronics', 3, 2400, 4900, 4, 10, 30),
(20, 'SKU-0020-USBF', 'USB Flash Drive 128GB', 'Electronics', 2, 900, 2200, 52, 15, 30),
(21, 'SKU-0021-NOTE', 'Notebook A5 Ruled', 'Office', 2, 250, 700, 60, 20, 30),
(22, 'SKU-0022-PRIN', 'Printer Paper Ream', 'Office', 2, 450, 1000, 8, 20, 30),
(23, 'SKU-0023-BALL', 'Ballpoint Pens (Box of 12)', 'Office', 2, 300, 800, 41, 15, 30),
(24, 'SKU-0024-STAP', 'Stapler', 'Office', 2, 350, 900, 17, 8, 30),
(25, 'SKU-0025-STIC', 'Sticky Notes Pack', 'Office', 2, 200, 550, 33, 15, 30),
(26, 'SKU-0026-BIND', 'Binder Clips (Box)', 'Office', 2, 150, 450, 29, 10, 30),
(27, 'SKU-0027-WHIT', 'Whiteboard Markers Set', 'Office', 2, 400, 950, 22, 10, 30),
(28, 'SKU-0028-DESK', 'Desk Organizer', 'Office', 2, 900, 2100, 13, 6, 30),
(29, 'SKU-0029-FILE', 'File Folders (Pack of 25)', 'Office', 2, 350, 850, 5, 12, 30),
(30, 'SKU-0030-ENVE', 'Envelopes (Box of 50)', 'Office', 2, 300, 750, 26, 10, 30),
(31, 'SKU-0031-CORR', 'Correction Tape', 'Office', 2, 180, 450, 19, 10, 30),
(32, 'SKU-0032-HIGH', 'Highlighters Set', 'Office', 2, 260, 650, 24, 10, 30),
(33, 'SKU-0033-PUSH', 'Push Pins (Box)', 'Office', 2, 120, 350, 31, 10, 30),
(34, 'SKU-0034-RUBB', 'Rubber Bands Bag', 'Office', 2, 100, 300, 40, 10, 30),
(35, 'SKU-0035-LABE', 'Label Maker Tape', 'Office', 2, 500, 1200, 9, 8, 30),
(36, 'SKU-0036-SCIS', 'Scissors', 'Office', 2, 280, 700, 21, 8, 30),
(37, 'SKU-0037-TAPE', 'Tape Dispenser', 'Office', 2, 220, 600, 18, 8, 30),
(38, 'SKU-0038-CLIP', 'Clipboard', 'Office', 2, 260, 650, 16, 6, 30),
(39, 'SKU-0039-DESK', 'Desktop Calculator', 'Office', 2, 600, 1400, 12, 6, 30),
(40, 'SKU-0040-LEDD', 'LED Desk Lamp', 'Office', 2, 1400, 2900, 10, 6, 30);

INSERT INTO "inventory_movements" ("product_id", "type", "quantity_delta", "note", "actor", "created_at") VALUES

(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(1, 'sale', -2, NULL, 'human', NOW() - INTERVAL '28 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(1, 'sale', -2, NULL, 'human', NOW() - INTERVAL '7 days'),
(1, 'sale', -2, NULL, 'human', NOW() - INTERVAL '6 days'),
(1, 'sale', -2, NULL, 'human', NOW() - INTERVAL '5 days'),
(1, 'sale', -2, NULL, 'human', NOW() - INTERVAL '4 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(1, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(1, 'sale', -2, NULL, 'human', NOW() - INTERVAL '1 days'),
(1, 'restock', 13, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(2, 'sale', -2, NULL, 'human', NOW() - INTERVAL '6 days'),
(2, 'sale', -2, NULL, 'human', NOW() - INTERVAL '5 days'),
(2, 'sale', -2, NULL, 'human', NOW() - INTERVAL '4 days'),
(2, 'sale', -2, NULL, 'human', NOW() - INTERVAL '3 days'),
(2, 'sale', -2, NULL, 'human', NOW() - INTERVAL '2 days'),
(2, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(3, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '29 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '24 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '23 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '22 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '21 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '20 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '19 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '17 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '14 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '12 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '7 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '5 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(4, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(4, 'sale', -2, NULL, 'human', NOW() - INTERVAL '1 days'),
(4, 'restock', 17, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(5, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(6, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(7, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(7, 'restock', 8, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(8, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(9, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(10, 'sale', -2, NULL, 'human', NOW() - INTERVAL '28 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(10, 'sale', -2, NULL, 'human', NOW() - INTERVAL '23 days'),
(10, 'sale', -2, NULL, 'human', NOW() - INTERVAL '22 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(10, 'sale', -2, NULL, 'human', NOW() - INTERVAL '17 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(10, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(10, 'restock', 14, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(12, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(12, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(12, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(12, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(12, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(13, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(13, 'restock', 6, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(16, 'restock', 2, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(17, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '29 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '19 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '13 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '11 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '9 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '8 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '7 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '5 days'),
(19, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '3 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '2 days'),
(19, 'sale', -2, NULL, 'human', NOW() - INTERVAL '1 days'),
(19, 'restock', 16, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(20, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '29 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '25 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '23 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '22 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '21 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '20 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '17 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '15 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '12 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '11 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(21, 'sale', -2, NULL, 'human', NOW() - INTERVAL '2 days'),
(21, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '30 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '29 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '28 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '27 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '26 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '25 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '24 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '23 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '22 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '21 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '20 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '19 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '18 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '17 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '16 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '15 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '14 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '13 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '12 days'),
(22, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '10 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '9 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '8 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '7 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '6 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '5 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '4 days'),
(22, 'sale', -2, NULL, 'human', NOW() - INTERVAL '3 days'),
(22, 'sale', -3, NULL, 'human', NOW() - INTERVAL '2 days'),
(22, 'sale', -4, NULL, 'human', NOW() - INTERVAL '1 days'),
(22, 'restock', 29, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(23, 'sale', -2, NULL, 'human', NOW() - INTERVAL '24 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(23, 'sale', -2, NULL, 'human', NOW() - INTERVAL '22 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(23, 'sale', -2, NULL, 'human', NOW() - INTERVAL '12 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(23, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(25, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(25, 'restock', 11, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(26, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(26, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(26, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(26, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(26, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(26, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(27, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(28, 'restock', 2, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '30 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '29 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '23 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '7 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '5 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '2 days'),
(29, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '28 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '26 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '21 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '17 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '13 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '6 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(30, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(31, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(31, 'sale', -1, NULL, 'human', NOW() - INTERVAL '25 days'),
(31, 'sale', -1, NULL, 'human', NOW() - INTERVAL '20 days'),
(31, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(31, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(31, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(31, 'restock', 5, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '24 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '22 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '19 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '16 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '15 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '14 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '10 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '4 days'),
(32, 'sale', -1, NULL, 'human', NOW() - INTERVAL '3 days'),
(34, 'restock', 2, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '27 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '18 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '12 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '11 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '9 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '8 days'),
(35, 'sale', -1, NULL, 'human', NOW() - INTERVAL '1 days'),
(37, 'restock', 2, 'Routine restock', 'human', NOW() - INTERVAL '20 days'),
(40, 'restock', 2, 'Routine restock', 'human', NOW() - INTERVAL '20 days');

INSERT INTO "purchase_orders" ("id", "po_number", "supplier_id", "status", "notes", "created_by", "created_at", "approved_at", "received_at") VALUES

(1, 'PO-1040', 1, 'received', 'Routine electronics restock', 'human', NOW() - INTERVAL '18 days', NOW() - INTERVAL '17 days', NOW() - INTERVAL '12 days'),
(2, 'PO-1041', 2, 'approved', 'Office supplies top-up', 'human', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NULL);

INSERT INTO "purchase_order_items" ("purchase_order_id", "product_id", "quantity", "unit_cost_cents") VALUES

(1, 1, 20, 3200),
(1, 5, 15, 2600),
(2, 22, 40, 450),
(2, 29, 30, 350);
